export enum NotificationChannel {
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',       // Firebase Cloud Messaging
  EMAIL = 'EMAIL',     // Nodemailer
  SMS = 'SMS',         // Future
  WHATSAPP = 'WHATSAPP', // Future
  VOICE = 'VOICE',     // Future
}

export enum NotificationType {
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  QUEUE_UPDATES = 'QUEUE_UPDATES',
  NOW_SERVING = 'NOW_SERVING',
  YOUR_TURN = 'YOUR_TURN',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  SALON_CLOSED = 'SALON_CLOSED',
  EMERGENCY_CLOSURE = 'EMERGENCY_CLOSURE',
  PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL',
  REFUND_SUCCESSFUL = 'REFUND_SUCCESSFUL',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  OFFER_NOTIFICATION = 'OFFER_NOTIFICATION',
  SECURITY_ALERTS = 'SECURITY_ALERTS',
  SYSTEM_ANNOUNCEMENTS = 'SYSTEM_ANNOUNCEMENTS'
}
